15-CDI/src/de/christopherolbertz/di/view/CdiBean.java
package de.christopherolbertz.di.view;

import java.io.Serializable;
import java.util.Date;

import javax.enterprise.context.Dependent;
import javax.inject.Inject;
import javax.inject.Named;

import de.christopherolbertz.di.qualifier.MyDate;
import de.christopherolbertz.di.qualifier.MyQualifier;
import de.christopherolbertz.di.qualifier.Random;
import de.christopherolbertz.di.qualifier.RandomWithService;


@Named
@Dependent
public class CdiBean implements Serializable {
	@Inject
	private RequestBean requestBean = new RequestBean();
	@Inject
	@MyQualifier
	private Service service;
	@Inject
	private Service anotherService;
	@Inject
	@Named(value = "viewBean")
	private ViewBean viewBean;
	@Inject
	@Random
	private int random;
	@Inject
	@MyDate
	private Date currentDate;
	@Inject
	@RandomWithService
	private int anotherValue;
	
	public int getAnotherValue() {
		return anotherValue;
	}
	
	public void setAnotherValue(int anotherValue) {
		this.anotherValue = anotherValue;
	}
	
	public Date getCurrentDate() {
		return currentDate;
	}
	
	public void setCurrentDate(Date currentDate) {
		this.currentDate = currentDate;
	}
	
	public RequestBean getRequestBean() {
		return requestBean;
	}
	
	public void setRequestBean(RequestBean requestBean) {
		this.requestBean = requestBean;
	}
	
	public String getText() {
		return "Hallo CDI!";
	}
	
	public Service getService() {
		return service;
	}
	
	public void setService(Service service) {
		this.service = service;
	}
	
	public Service getAnotherService() {
		return anotherService;
	}
	
	public void setAnotherService(Service anotherService) {
		this.anotherService = anotherService;
	}
	
	public ViewBean getViewBean() {
		return viewBean;
	}
	
	public void setViewBean(ViewBean viewBean) {
		this.viewBean = viewBean;
	}
	
	public int getRandom() {
		return random;
	}
	
	public void setRandom(int random) {
		this.random = random;
	}
}

15-CDI/src/de/christopherolbertz/di/view/RequestBean.java
package de.christopherolbertz.di.view;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

@Named
@RequestScoped
public class RequestBean {
	public String getText() {
		return "Ich bin die Request-Bean";
	}
}

15-CDI/src/de/christopherolbertz/di/view/ViewBean.java
package de.christopherolbertz.di.view;

import java.io.Serializable;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named("viewBean")
@ViewScoped
public class ViewBean implements Serializable {
	public String getText() {
		return "Ich bin die View-Bean";
	}
}

15-CDI/WebContent/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core">

<h:head>
    <title><h:outputText value="CDI" /></title>
</h:head>

<h:body>
	<p><h:outputText value="#{cdiBean.text}" /></p>
	<p><h:outputText value="#{cdiBean.requestBean.text}" /></p>
	<p><h:outputText value="#{cdiBean.service.integer}" /></p>
	<p><h:outputText value="#{cdiBean.anotherService.integer}" /></p>
	<p><h:outputText value="#{cdiBean.viewBean.text}" /></p>
	<p><h:outputText value="#{cdiBean.random}" /></p>
	<p><h:outputText value="#{cdiBean.currentDate}">
		<f:convertDateTime pattern="dd.MM.yyyy hh:mm:ss" />
	</h:outputText></p>
	<p><h:outputText value="#{cdiBean.anotherValue}" /></p>
</h:body>
</html>