11-Ajax/src/de/christopherolbertz/ajax/view/ColorBean.java
package de.christopherolbertz.ajax.view;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean
@ViewScoped
public class ColorBean {
	private String selectedColor;

	public String getSelectedColor() {
		return selectedColor;
	}

	public void setSelectedColor(String selectedColor) {
		this.selectedColor = selectedColor;
	}
	
	public String getColor() {
		if (selectedColor == null) {
			return "Keine Farbe gewaehlt!";
		} else {
			return "Farbe: " + selectedColor;
		}
	}
	
	public String getColorStyle() {
		return "background-color: " + selectedColor;
	}
}

11-Ajax/src/de/christopherolbertz/ajax/view/EventBean.java
package de.christopherolbertz.ajax.view;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.event.AjaxBehaviorEvent;

@ManagedBean
@ViewScoped
public class EventBean {
	private int zahlQuersumme;
	private int quersumme;
	private String style;
	private String position; 
	
	public void berechneQuersumme(AjaxBehaviorEvent ajaxBehaviorEvent) {
		int zahl = zahlQuersumme;
		quersumme = 0;
		
		while (zahl > 0) {
			quersumme = quersumme + zahl % 10;
			zahl = zahl / 10;
		}
	}
	
	public void onMouseOver(AjaxBehaviorEvent ajaxBehaviorEvent) {
		style = "color:red;";
	}
	
	public void onMouseOut(AjaxBehaviorEvent ajaxBehaviorEvent) {
		style = "color:green;";
	}
	
	public void onDblClick(AjaxBehaviorEvent ajaxBehaviorEvent) {
		int positionZahl = getZufallszahl(1000);
		String farbe = farbenGenerator();
		position = "position:absolute;left:" + positionZahl + "px;"
				+ "background-color:" + farbe;
	}
	
	private int getZufallszahl(int grenze) {
		return (int)(Math.random() * grenze); 
	}
	
	private String farbenGenerator() {
		int zahl = getZufallszahl(5);
		String farbe = "";
		switch(zahl) {
			case 1: 	farbe = "red";
							break;
			case 2: 	farbe = "yellow";
			  				break;
			case 3: 	farbe = "green";
			  				break;
			case 4: 	farbe = "black";
			  				break;
			case 5: 	farbe = "blue";
			  				break;
		}
		return farbe;
	}
	
	public int getZahlQuersumme() {
		return zahlQuersumme;
	}

	public void setZahlQuersumme(int zahlQuersumme) {
		this.zahlQuersumme = zahlQuersumme;
	}

	public int getQuersumme() {
		return quersumme;
	}

	public String getStyle() {
		return style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}
}

11-Ajax/WebContent/events.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core">

<h:head>
	<title>JavaScript-Ereignisse</title>
</h:head>

<h:body>
	<f:view>
 	<h:form id="form">
 		<h:outputLabel value="keyupEvent: " for="txtQuersumme" />
 		<h:inputText value="#{eventBean.zahlQuersumme}" id="txtQuersumme">
 			<f:ajax listener="#{eventBean.berechneQuersumme}"
 					event="keyup"
 					render="lblQuersumme" />
 		</h:inputText>
	</h:form>
	<h:outputText value="#{eventBean.quersumme}" id="lblQuersumme" />
	
	<h:outputLabel id="lblMaus" value="Bewege die Maus über mich!"
				  style="#{eventBean.style}">
		<f:ajax listener="#{eventBean.onMouseOver}"
				event="mouseover"
				render="lblMaus" />
		<f:ajax listener="#{eventBean.onMouseOut}"
				event="mouseout"
				render="lblMaus" />
	</h:outputLabel>
	
	<br />
	<h:outputLabel value="Fang mich mit Doppelklick!" id="lblFang"
				   style="#{eventBean.position}">
		<f:ajax event="dblclick" listener="#{eventBean.onDblClick}"
				render="lblFang" />
	</h:outputLabel>
	</f:view>
</h:body>
</html>

11-Ajax/WebContent/konto.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
      
	<h:head>
		<title>Ajax-Beispiel für execute="@form"</title>
	</h:head>
	<h:body>
		<h:form>
			Kundennummer:
			<h:inputText value="#{bankingBeanAjax.customerId}" /><br />
			Passwort:
			<h:inputSecret value="#{bankingBeanAjax.password}" />
					
			<h:commandButton value="Zeige Kontostand" 
							 actionListener="#{bankingBeanAjax.showBalance}">
				<f:ajax render="ajaxMessage" execute="@form"/>
			</h:commandButton>
			
			<h2><h:outputText value="#{bankingBeanAjax.message}" 
												    id="ajaxMessage" /></h2>
		</h:form>
	</h:body>
</html>

11-Ajax/WebContent/render.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core">

<h:head>
	<title>Farb-Waehler</title>
</h:head>

<h:body>
	<f:view>
	 	<h:form id="form">
			<h:selectOneMenu value="#{colorBean.selectedColor}">
				<f:selectItem itemLabel="Rot" itemValue="red" />
				<f:selectItem itemLabel="Gelb" itemValue="yellow" />
				<f:selectItem itemLabel="Schwarz" itemValue="black" />
				<f:selectItem itemLabel="Blau" itemValue="blue" />
				<f:selectItem itemLabel="Grau" itemValue="grey" />
				<f:selectItem itemLabel="Grün" itemValue="green" />
				<f:ajax render="lblColor" />
			</h:selectOneMenu>
			<br />
			<h:outputLabel value="#{colorBean.color}" id="lblColor"
						   style="#{colorBean.colorStyle}" />
		</h:form>
	</f:view>
</h:body>
</html>

11-Ajax/WebContent/render2.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core">

<head>
	<title>Zeichen-Zaehler</title>
</head>

<body>
	<f:view>
		<h:form id="frmRegistration">
				<h:outputText value="Bitte geben Sie einen Text ein" /> 
				<h:inputText value="#{charCounterBean.text}" id="txtInput" valueChangeListener="#{charCounterBean.countChars}">
					<f:ajax render="lblCharCounter" />
				</h:inputText>
				<br />
				<br />								
				<h:outputText value="#{charCounterBean.counter}" id="lblCharCounter" />
		</h:form>
	</f:view>
</body>
</html>

11-Ajax/WebContent/zufallszahlen.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
      
	<h:head>
		<title>Ajax-Beispiel für execute</title>
	</h:head>
	<h:body>
		<h3>Zeige mir eine Zufallszahl</h3>
			<h:form>
				Bereich: <h:inputText value="#{numberGeneratorBean.range}" id="txtRange" />
				<h:commandButton value="Zeige Zahl" 
								 actionListener="#{numberGeneratorBean.randomize}">
					<f:ajax render="lblNumber" execute="txtRange" />
				</h:commandButton>
				
				<h2><h:outputText value="#{numberGeneratorBean.randomNumber}" 
								  id="lblNumber"/></h2>
			</h:form>
	</h:body>
</html>