8-JsfKonvertierung/src/de/christopherolbertz/jsfkonvertierung/view/CalculatorBean.java
package de.christopherolbertz.jsfkonvertierung.view;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ActionEvent;

/**
 * Eine kleine Taschenrechner-Bean, die die Konvertierung von einfachen Datentypen 
 * demonstriert.
 * @author Christopher
 *
 */
@ManagedBean
@ViewScoped
public class CalculatorBean {
	private int number2;
	private int number1;
	private double result;
	private String operator;
	
	public void calculate(ActionEvent actionEvent) {
		if (operator.equals("+")) {
			result = number1 + number2;
		} else if (operator.equals("-")) {
			result = number1 - number2;
		} else if (operator.equals("*")) {
			result = number1 * number2;
		} else {
			result = number1 / (double)number2;
		}
	}
	
	public int getNumber2() {
		return number2;
	}
	
	public void setNumber2(int number2) {
		this.number2 = number2;
	}
	
	public int getNumber1() {
		return number1;
	}
	
	public void setNumber1(int number1) {
		this.number1 = number1;
	}
	
	public double getResult() {
		return result;
	}
	
	public void setResult(double result) {
		this.result = result;
	}
	
	public String getOperator() {
		return operator;
	}
	
	public void setOperator(String operator) {
		this.operator = operator;
	}
}

8-JsfKonvertierung/src/de/christopherolbertz/jsfkonvertierung/view/NumberBean.java
package de.christopherolbertz.jsfkonvertierung.view;

import javax.faces.bean.ManagedBean;

import de.christopherolbertz.jsfkonvertierung.spacegame.utils.RandomUtils;

@ManagedBean
public class NumberBean {
	private int inputValue;
	
	public double getDoubleValue() {
		return 17.12345678;
	}
	
	public double getValue() {
		return RandomUtils.randomDouble();
	}
	
	public int getInputValue() {
		return inputValue;
	}
	
	public void setInputValue(int inputValue) {
		this.inputValue = inputValue;
	}
}

8-JsfKonvertierung/WebContent/pages/calculator.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core">

<head>
	<title>Ein kleiner Taschenrechner</title>
</head>

<body>
	<f:view>
		<h:form>
			<h:outputText value="Bitte Zahlen eingeben: " />
			<br />
			<h:inputText value="#{calculatorBean.number1}" />
			
			<h:selectOneMenu value="#{calculatorBean.operator}">
				<f:selectItem itemLabel="+" itemValue="+" />
				<f:selectItem itemLabel="-" itemValue="-" />
				<f:selectItem itemLabel="*" itemValue="*" />
				<f:selectItem itemLabel="/" itemValue="/" />
			</h:selectOneMenu>
			
			<h:inputText value="#{calculatorBean.number2}" />
			
			<h:outputText value="= #{calculatorBean.result}" />
			<br />
			<h:commandButton value="Rechne" actionListener="#{calculatorBean.calculate}" />
		</h:form>
	</f:view>
</body>
</html>

8-JsfKonvertierung/WebContent/pages/dateTimeConverter.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core">
      

<head>
	<title>Datum und Uhrzeit konvertieren</title>
</head>
<h:body>
	<f:view>
		<h:form>
			<h:panelGrid columns="2">
				<h:outputLabel value="Datum und Uhrzeit im Format dd.MM.yyyy eingeben: " />
				<h:inputText value="#{dateTimeView.date}">
					<f:convertDateTime pattern="dd.MM.yyyy" />
				</h:inputText>
				
				<h:commandButton value="Los!" />
				
				<h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime type="date" />				
				</h:outputText>
			</h:panelGrid>
		</h:form>
		
		<h:form>
			<h:panelGrid columns="2">
				<h:outputLabel value="Datum und Uhrzeit im Format dd.MM.yyyy hh:mm:ss eingeben: " />
				<h:inputText value="#{dateTimeView.date}">
					<f:convertDateTime pattern="dd.MM.yyyy hh:mm:ss" />
				</h:inputText>
				
				<h:commandButton value="Los!" />
				
				<h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime type="both" />				
				</h:outputText>
			</h:panelGrid>
		</h:form>
		

		<h1>Attribute dateStyle und type</h1>			
		<table border="1">
			<tr><th>short</th><th>medium</th><th>long</th><th>full</th><th>full both</th><th>long both</th></tr>
			<tr>
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime dateStyle="short" />				
				</h:outputText>
				</td>
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime dateStyle="medium" />				
				</h:outputText>
				</td>						
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime dateStyle="long" />				
				</h:outputText>
				</td>						
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime dateStyle="full" />				
				</h:outputText>
				</td>
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime dateStyle="full" type="both" />				
				</h:outputText>
				</td>
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime dateStyle="long" type="both" />				
				</h:outputText>
				</td>											
			</tr>
		</table>
		
		<h1>Verschiedene Zeitzonen</h1>
		<table border="1">
			<tr><th>Honolulu</th><th>Hobart</th><th>Paris</th><th>Tokio</th><th>Maseru</th><th>Los Angeles</th><th>Davis</th></tr>
			<tr>
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime timeZone="Pacific/Honolulu" type="both" />				
				</h:outputText>
				</td>
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime timeZone="Australia/Hobart" type="both" />				
				</h:outputText>
				</td>						
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime timeZone="Europa/Paris" type="date" />				
				</h:outputText>
				</td>			
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime timeZone="Asia/Tokyo" pattern="dd.MM.yyyy, E" />				
				</h:outputText>
				</td>										
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime timeZone="Africa/Maseru" type="both" />				
				</h:outputText>
				</td>
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime timeZone="America/Los_Angeles" type="both" />				
				</h:outputText>
				</td>
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime timeZone="Antartica/Davis" type="both" />				
				</h:outputText>
				</td>											
			</tr>
		</table>		
		
		<h1>Einige Patterns</h1>
		<table border="1">
			<tr><th>dd.MM.yyyy</th><th>yyyy.MM.dd</th><th>'Heute,' EEEE 'der' dd. MMMM yyyy</th><th>'Datum:' dd.MM.yyyy G 'Uhrzeit:' HH:mm:ss:SSS</th></tr>
			<tr>
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime pattern="dd.MM.yyyy" />				
				</h:outputText>
				</td>
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime pattern="yyyy.MM.dd" />				
				</h:outputText>
				</td>
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime pattern="'Heute,' EEEE 'der' dd. MMMM yyyy" />				
				</h:outputText>
				</td>						
				<td><h:outputText value="#{dateTimeView.date}">
					<f:convertDateTime pattern="'Datum:' dd.MM.yyyy G 'Uhrzeit:' HH:mm:ss:SSS" />				
				</h:outputText>
				</td>			
				<td>
				</td>										
			</tr>
		</table>						
		<h:messages showDetail="true" />
	</f:view>
</h:body>
</html>

8-JsfKonvertierung/WebContent/pages/numberConverter.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core">
      

<head>
	<link rel="stylesheet" href="#{request.contextPath}/css/style.css" type="text/css" />
	<title>Der NumberConverter</title>
</head>
<h:body>
<f:view>
	<h:form>
		<h1>Lokalisierung</h1>			
		<table border="1">
			<tr><th>deutsch</th><th>amerikanisch</th></tr>
			<tr>
				<td>
					<h:outputText value="#{numberBean.value}">
						<f:convertNumber locale="de" />
					</h:outputText>
				</td>
				<td>
					<h:outputText value="#{numberBean.value}">
						<f:convertNumber locale="en_US" />
					</h:outputText>
				</td>															
			</tr>
		</table>
		
		<h1>Attribut type</h1>			
		<table border="1">
			<tr><th>number</th><th>percent</th><th>Geld</th></tr>
			<tr>
				<td>
					<h:outputText value="#{numberBean.value}">
						<f:convertNumber type="number" />
					</h:outputText>
				</td>
				<td>
					<h:outputText value="#{numberBean.value}">
						<f:convertNumber type="percent" />
					</h:outputText>				
				</td>
				<td>
					<h:outputText value="#{numberBean.value}">
						<f:convertNumber type="currency" locale="en_US" />
					</h:outputText>				
				</td>																								
			</tr>
		</table>
		
		<h1>Geld macht immer Spaß</h1>			
		<table border="1">
			<tr><th>EUR</th><th>€</th><th>XXX</th><th>$</th></tr>
			<tr>
				<td>
					<h:outputText value="#{numberBean.value}">
						<f:convertNumber type="currency" currencyCode="EUR" />
					</h:outputText>					
				</td>
				<td>
					<h:outputText value="#{numberBean.value}">
						<f:convertNumber type="currency" currencySymbol="€" />
					</h:outputText>					
				</td>
				<td>
					<h:outputText value="#{numberBean.value}">
						<f:convertNumber type="currency" currencyCode="XXX" locale="en_US" />
					</h:outputText>					
				</td>	
				<td>
					<h:outputText value="#{numberBean.value}">
						<f:convertNumber type="currency" currencySymbol="$" />
					</h:outputText>					
				</td>																											
			</tr>
		</table>		
	
		<h1>Attribut pattern</h1>			
		<table border="1">
			<tr><th>###,###.##</th><th>######## 'm'</th><th>00000000 'm'</th>
				<th>pattern="####0000</th></tr>
			<tr>
				<td>
					<h:outputText value="#{numberBean.doubleValue}">
						<f:convertNumber pattern="###,###.##" />
					</h:outputText>								
				</td>
				<td>
					<h:outputText value="#{numberBean.doubleValue}">
						<f:convertNumber pattern="######## 'm'" />
					</h:outputText>					
				</td>
				<td>
					<h:outputText value="#{numberBean.doubleValue}">
						<f:convertNumber pattern="00000000 'm'" />
					</h:outputText>					
				</td>	
				<td>
					<h:outputText value="#{numberBean.doubleValue}">
						<f:convertNumber pattern="####0000" />
					</h:outputText>					
				</td>																											
			</tr>
		</table>			
		
		<h1>Konvertierung bei Eingabe</h1>
		<p>Mit welcher Geschwindigkeit möchten Sie fliegen? </p>
		<h:inputText value="#{numberBean.inputValue}">
			<f:convertNumber pattern="######## 'km / s'" />
		</h:inputText>
		<h:commandButton value="ok" />
		
		<br />
		<h:outputLabel value="#{numberBean.inputValue}">
			<f:convertNumber pattern="######## 'km / s'" />
		</h:outputLabel>
		
				<br />
		<h:outputLabel value="#{numberBean.inputValue}">
			<f:convertNumber pattern="########" />
		</h:outputLabel>
	</h:form>
</f:view>
</h:body>
</html>

8-JsfKonvertierung/WebContent/pages/pkConverterGlobal.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core">
      

<h:head>
	<link rel="stylesheet" href="#{request.contextPath}/css/style.css" type="text/css" />
	<title>Globaler anwendungsdefinierter Konvertierer</title>
</h:head>
<h:body>
	<h:form>
		<h:panelGrid columns="3">
			<h:outputText value="Bitte geben Sie eine Bundeswehr-PK ein: " />
			<h:inputText value="#{pkConverterView.pk}" id="txtPk" />
			<h:message for="txtPk" />
			
			<h:commandButton value="Senden" />
			<h:outputText value="Gelesen wurde Pk #{pkConverterView.pk.toString()}" />
		</h:panelGrid>
	</h:form>
</h:body>
</html>

8-JsfKonvertierung/WebContent/pages/pkConverterLocal.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core">
      

<h:head>
	<link rel="stylesheet" href="#{request.contextPath}/css/style.css" type="text/css" />
	<title>Lokaler anwendungsdefinierter Konvertierer</title>
</h:head>
<h:body>
	<h:form>
		<h:panelGrid columns="3">
			<h:outputText value="Bitte geben Sie eine Bundeswehr-PK ein: " />
			<h:inputText value="#{pkConverterView.pk}" id="txtPk">
				<f:converter converterId="pkConverter" />
			</h:inputText>
			<h:message for="txtPk" />
			
			<h:commandButton value="Senden" />
			<h:outputText value="Gelesen wurde Pk #{pkConverterView.pk}" />
		</h:panelGrid>
	</h:form>
	
	<h:form>
		<h:panelGrid columns="3">
			<h:outputText value="Bitte geben Sie eine Bundeswehr-PK ein: " />
			<h:inputText value="#{pkConverterView.pk2}" id="txtPk2" />
			<h:message for="txtPk" />
			
			<h:commandButton value="Senden" />
			<h:outputText value="Gelesen wurde Pk #{pkConverterView.pk2}" />
		</h:panelGrid>
	</h:form>	
</h:body>
</html>